Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('cart/', include('cart.urls',namespace='cart')),
    # path('manageorder/', include('admin.urls', namespace='admin')),
    path('',include('main.urls',namespace='main')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django import urls
from django.urls import path
from django.urls.conf import include
from . import views

app_name='cart'

extra_patterns = [
    path('add/carts/<int:product_id>/', views.cart_add, name='cart_add'),
]

urlpatterns=[
   
    path ('add/',include(extra_patterns)),
    path ('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('ordersummary/',views.order_summary,name='order-summary'),
    path ('',views.cart_detail,name='cart_detail'),

]

cart/forms.py
from django import forms



PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,widget=forms.Select(attrs={'style': 'width: 95px !important; resize: vertical !important;','class': 'form-select'}))
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
import re

from django.http.response import HttpResponseRedirect
from cart.forms import CartAddProductForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from main.models import Products,transactions
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
@csrf_exempt
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(transactions, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        print(cd)
        cart.add(product=product, quantity=cd['quantity'])
    else:
        print('error')
    print(cart)

    # request.session['items_total'] = cart.product.count()
    return HttpResponseRedirect(reverse('main:home'),'success')
    # return redirect('main:home')

def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(transactions, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    if not cart:
        return render(request,'main/emptycart.html')
    else:
        return render (request ,'cart/cartdetail.html',{'cart':cart})

def order_summary(request):
    cart = Cart(request)
    return render(request,'cart/orderSummary.html',{'cart':cart})
    

cart/templates/cart/cartdetail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}

<div class="container my-5">
 <div class="row">
  <h1 class="text-center mb-5">Shopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3>
    {% for items in cart %}
    {% with product=items.product %}
    <div class="row">
     <div class="col-sm-3 text-center align-self-center">
       <img src={{product.productID.product_image.url}} alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150">
      </div>
     <div class="col-sm-9">
      <div>
       <h5>{{product.productID.name}}</h5>
       <p class="mb-2 text-muted small">Description: {{product.Description}}</p>
       <div class="my-3">
        <label for="quantity">Quantity: {{items.quantity}}</label>
        <label for="disount">Discount: {{items.discountPercent}} %</label>
        <!-- <a class="minus-cart btn" pid="{{cart.productID.id}}"><i class="fas fa-minus-square fa-lg"></i></a> -->
        <!-- <a class="minus-cart btn"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">{{item.quantity}}</span>
          <a class="plus-cart btn"><i class="fas fa-plus-square fa-lg"></i></a> -->
        <!-- <a class="plus-cart btn" pid="{{cart.productID.id}}"><i class="fas fa-plus-square fa-lg"></i></a> -->
       </div> 
       <div class="d-flex justify-content-between">
           <form action="{% url 'cart:cart_remove' product.id %}" method="post">
               <input type="submit" class="btn btn-sm btn-secondary mr-3" value="Remove Item">
               {% csrf_token %}
           </form>
        <!-- <a class="btn btn-sm btn-secondary mr-3 remove-cart" pid="{{cart.productID.id}}"><strong>Remove Item</strong>  </a> -->
        <p class="mb-0"><span><strong>Rs. {{items.total_price}} </strong></span></p>
        <p class="mb-0"><span><strong>After Discount: Rs. {{items.total_after_discount}} </strong></span></p>
       </div>
      </div>
     </div>
    </div>
    {% endwith %}
    {% endfor %}
    </div>
    </div>
  </div>

  <div class="col-sm-4">
   <div class="card">
    <div class="card-body">
      <h3>Total Amount</h3>
      <ul class="list-group">
       <!-- <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount<span>Rs. <span id="amount">{{amount}}</span></span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>Rs. 70.00</span></li> -->
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total Cost</strong>
         </div>
         <span><strong>Rs. {{cart.get_total_price}}</strong></span>
       </li>
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total After Discount</strong>
         </div>
         <span><strong>Rs. {{cart.get_total_price_discount}}</strong></span>
       </li>
      </ul>
      <div class="d-grid"><a href="{% url 'main:home' %}" class="btn btn-primary">Continue Shopping</a></div>
      <div class="d-grid"><a href="{% url 'cart:order-summary' %}" class="btn btn-primary">Continue</a></div>
    </div>
   </div>
  </div>
  
 </div>
</div>
{% endblock main-content %}

cart/templates/cart/orderSummary.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Order Summary{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row mt-5">
    <h4>Order Summary</h4>
    <hr>
    <table>
      <thead>
        <tr>
          <td></td>
          <td><h5>Product Name</h5></td>
          <td><h5>Detail</h5></td>
          <td><h5>Quantity</h5></td>
          <td><h5>Price</h5></td>
          <td><h5>Discount</h5></td>
          <td><h5>Total</h5></td>
          <!-- <td></td> -->
        </tr>
      </thead>
      <tbody> 
        {% for items in cart %}
        {% with product=items.product %}
        <tr>
          <td>
            <img src={{product.productID.product_image.url}} alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150">
          </td>
          <td>
           <h5>{{product.productID.name}}</h5>
          </td>
          <td>
            {{product.Description}}
           </td>
          <td>
            {{items.quantity}}
          </td>
          <td>
            Rs. {{items.total_price}}
          </td>
          <td>
            {{items.discountPercent}} %
          </td>
          <td>
            {{items.total_after_discount}}
          </td>
          <!-- <td>
            <a class="remove" href="/cart/change?line=1&amp;quantity=0" data-id="39368016003152">X</a>
          </td> -->
        </tr>
        {% endwith %}
        {% endfor %}
      </tbody>
    </table>
    <!-- <small>Term and Condition: Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia, ullam saepe! Iure optio repellat dolor velit, minus rem. Facilis cumque neque numquam laboriosam, accusantium adipisci nisi nihil in et quis?</small> -->
  </div>
<div class="text-end">
    <p><strong>Total Amount:</strong> {{cart.get_total_price_discount}}</p>
</div>
<form action="{% url 'main:checkout' %}">
    <div class="text-end">
      <button type="submit" class="btn btn-warning mt-3 px-5 fw-bold">Place Order</button>
    </div>
</form>
  <!-- <div class="col-sm-4 offset-sm-1">
    <h4>Shipping Address</h4>
    <hr>
    {% for ad in address %}
      <div class="card">
        <div class="card-body">
        <h5>{{ad.name}}</h5>
        <p>{{ad.address}}</p>
        <p>{{ad.phone}}</p>
        </div>
        {% endfor %}
        <div class="d-grid"><a href="{% url 'main:orders' %}" class="btn btn-primary">Continue</a></div>
      </div>
       
    </div> -->
  </div>
{% endblock main-content %}