Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('cart/', include('cart.urls',namespace='cart')),
    # path('manageorder/', include('admin.urls', namespace='admin')),
    path('',include('main.urls',namespace='main')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django import urls
from django.urls import path
from django.urls.conf import include
from . import views

app_name='cart'

extra_patterns = [
    path('add/carts/<int:product_id>/', views.cart_add, name='cart_add'),
]

urlpatterns=[
   
    path ('add/',include(extra_patterns)),
    path ('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('ordersummary/',views.order_summary,name='order-summary'),
    path ('',views.cart_detail,name='cart_detail'),

]

main/models.py
from django.db.models.aggregates import Count
from django.urls import reverse
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Customer(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.TextField()
    phone = models.CharField(max_length=15)
    # useremail = models.CharField(max_length=50)
    # password = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)

Order_Status = (
    ('Pending','Pending'),
    ('Processed',"Processed"),
    ('Completed','Completed'),
    ('Cancel','Cancel')
)

class Orders(models.Model):
    customerID = models.ForeignKey(Customer, on_delete=models.CASCADE)
    Order_Date = models.DateTimeField(auto_now_add=True)
    orderStatus = models.CharField(max_length=50,choices=Order_Status, default='Pending')

    def __str__(self):
        return str(self.customerID)

    def getOrderCount(self,id):
        orders = Orders.objects.filter(orderStatus="Processed",customerID=id).values('customerID').annotate(dcount=Count('id'))
        return orders

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return str(self.name)

class Sub_Category(models.Model):
    CategoryID = models.ForeignKey(Category, related_name='subcategoryies', on_delete=models.CASCADE, blank=True, null=True)
    sub_category_name = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('VegetablesData', args=[str(self.sub_category_name)])

    def __str__(self):
        return str(self.sub_category_name)


class CountingUnit(models.Model):
    unit = models.CharField(max_length=50)

    def __str__(self):
        return str(self.unit)

class Products(models.Model):
    Sub_Category_ID = models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
    # countingUnit = models.ForeignKey(CountingUnit,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    product_image = models.ImageField(upload_to='ProductImg')

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])

    def __str__(self):
        return str(self.name)

Status = (
    ('Enable','Enable'),
    ('Disable','Disable'),
)

class transactions(models.Model):
    productID = models.ForeignKey(Products ,on_delete=models.CASCADE)
    AUID = models.ForeignKey(CountingUnit,on_delete=models.CASCADE)
    Description = models.TextField()
    Price = models.FloatField()
    discount_percentage = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=50,choices=Status, default='Enable')

    def get_sale(self):
        selling_price = int(self.Price * (100 - self.discount_percentage) / 100)
        return selling_price

class OrderDetails(models.Model):
    orderID = models.ForeignKey(Orders, on_delete=models.CASCADE)
    productID = models.ForeignKey(transactions, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.FloatField()


class ContactUs(models.Model):
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.TextField()

class AboutUs(models.Model):
    Address = models.CharField(max_length=200)
    Number = models.CharField(max_length=50)
    email = models.CharField(max_length=100)

class TermAndConditions(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    updated_date = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateField()

class PrivacyPolicy(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    updated_date = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateField()

main/forms.py
from main.models import Customer,Orders
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from .models import Customer
from django.db.models import fields
from django.forms import widgets
from django.forms.fields import EmailField

class CustomerRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confrim Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields =['username','email','password1','password2']
        labels= {'email':'Email'}
        widgets = {'username':forms.TextInput(attrs={'class':'form-control'})}

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True , 'class':'form-control'}))
    password = forms.CharField(label=_("Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password' , 'class':'form-control'}))


class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'autofocus':True,'class':'form-control'}))
    new_password1 = forms.CharField(label=_("New Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'form-control'}),help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'form-control'}))

class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label=_("Email"),max_length=254,widget=forms.EmailInput(attrs={'autocomplete':'email','class':'form-control'}))

class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label=_("New Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'form-control'}),help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'form-control'}))

class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name','address','phone']
        widgets = {'name': forms.TextInput(attrs={'class':'form-control'}),
        'address' : forms.TextInput(attrs={'class':'form-control'}),
        'phone' : forms.TextInput(attrs={'class':'form-control'})}

class OrderForm(forms.ModelForm):
    class Meta:
        model=Orders
        fields=['orderStatus']

main/templates/main/Dried.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}

<!-- Start Banner -->
<div class="hero-wrap hero-bread" style="background-image: url('{% static 'main/images/category-4.jpg' %}');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Products</span></p>
        <h1 class="mb-0 bread">Fruits</h1>
      </div>
    </div>
  </div>
</div>
<!-- End Banner -->

<div class="container my-5">
 <div class="row">
  <div class="col-sm-3">
    <div class="list-group">
        <a href="{% url 'main:Dried' %}" class="list-group-item list-group-item-action" aria-current="true">
            All
        </a>
        <a href="{% url 'main:DriedData' 'Winter_Season' %}" class="list-group-item list-group-item-action" aria-current="true">
          Winter Season
        </a>
        <a href="{% url 'main:DriedData' 'Below' %}" class="list-group-item list-group-item-action" aria-current="true">
            Below 500
        </a>
        <a href="{% url 'main:DriedData' 'Above' %}" class="list-group-item list-group-item-action" aria-current="true">
            Above 500
        </a>
    </div>
  </div>
  <div class="col-sm-8 offset-sm-1">
    <div class="row">
        {% for product in dried %}
        <div class="col-sm-4">
         <div class="product">
           <a href="{% url 'main:product-detail' product.id %}" class="img-prod"><img class="img-fluid" src={{product.product_image.url}} alt="" height="200px">
             <span class="status">{{product.discount_percentage}}%</span>
             <div class="overlay"></div>
           </a>
           <div class="text py-3 pb-4 px-3 text-center">
             <h3><a href="#">{{product.name}}</a></h3>
             <div class="d-flex">
               <div class="pricing">
                 <p class="price"><span class="mr-2 price-dc">Rs. {{product.selling_price}}</span><span class="price-sale">Rs. {{product.get_sale}}</span></p>
               </div>
             </div>
             <div class="bottom-area d-flex px-3">
               <div class="m-auto d-flex">
                <form action="{% url 'cart:cart_add' product.id %}" class="d-inline" method="post">
                  <input type="submit" class="btn btn-primary shadow px-5 py-2" value="Add To Cart">
                  {{cart_product_form}}
                  {% csrf_token %}
                  
                  <!-- <button type="submit" class="btn btn-primary shadow px-5 py-2">Add to Cart</button> -->
                </form>
               </div>
             </div>
           </div>
         </div>
       </div>
        {% endfor %}
    </div>
  </div>
 </div>
</div>
{% endblock main-content %}

main/templates/main/admin_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


  <style type="text/css">
    .bs-example {
      margin: 0px;

    }

    .navbar-brand {
      font-size: 20px;
      font-family: sans-serif;

    }

        /*---------------------------------------
           Social section
        -----------------------------------------*/
        footer {
          padding: 0px 0px 0px 0px;
          background-color: black;
          margin: 0px;
        }


        #ftr {

          padding: 20px;
        }

        .fa {

          font-size: 23px;
          width: 60px;
          text-align: center;
          text-decoration: none;
          margin: 5px 2px;
          border-radius: 50%;
        }

        .fa:hover {
          opacity: 0.5;
          text-decoration: none;
        }

        .fa-facebook {
          background: #aadca2;
          color: white;
          margin-top: 30px;
        }

        .fa-whatsapp {
          background: #aadca2;
          color: white;
        }

        .fa-twitter {
          background: #aadca2;
          color: white;
        }

        .fa-instagram {
          background: #aadca2;
          color: white;
        }

        p {
          text-align: center;

        }
  </style>
</head>

<body>



  <div class="bs-example">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#5fe34b;">
      <a href="/" class="navbar-brand">Ecommerce</a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
        <div class="navbar-nav">
          <!-- <a href="/view-customer" class="nav-item nav-link">Customer</a> -->
          <a href="{% url 'main:admindashboard' %}" class="nav-item nav-link">Orders</a>
          <!-- <a href="/admin-products" class="nav-item nav-link">Products</a>
          <a href="/view-feedback" class="nav-item nav-link">Feedback</a> -->
        </div>

        <div class="navbar-nav navbar-right">
          <a href="{% url 'main:logout' %}" class="nav-item nav-link">LOGOUT</a>
        </div>

      </div>
    </nav>
  </div>

  <!-- content start-->
  {% block content %}

  {% endblock content %}
  <!-- content end-->
<br><br><br><br><br><br><br><br>
  <footer>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <div style="color:#ffffff;" class="wow fadeInUp footer-copyright">
            <p> <br>
              Copyright &copy; 2021 </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

  
 
 
</body>
</html>

main/templates/main/admin_dashboard.html
{% extends 'main/admin_base.html' %}
{% load static %}
{% load tags %}
{% block content %}
<br>
{%include 'main/admin_dashboard_cards.html'%}
<br><br><br><br><br>

<!-- <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" 
          integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" 
            crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
  $("#Id_submit").on("click", function (event) {
       event.preventDefault();
       //get closest outer div.. 
       var selector = $(this).closest(".OrderDIV")
       //find to get required elements..
      //  selector.find('.id_price').text($(this).children(":selected").attr("price"));
      //  selector.find('.price-sale').text($(this).children(":selected").attr("sale_price"));
      //  selector.find('.id_discount').text($(this).children(":selected").attr("discount"));
       let id = selector.attr('id_val');
       console.log(id);
      //  let Url = `{% url 'cart:cart_add' 0 %}`.replace(0, id);
      //  selector.find("form").attr('action', Url);
   });
  });

</script> -->



<hr><hr>

<div class="container" >
  <div class="row" style="text-align:center;" >
    <!-- Filter buttons -->
    <div class="col text-center">
      <a href="{% url 'main:adminOrdersfilter' 'Pending'  %}" class="btn btn-primary" style="width: 150px;">Pending</a>
      <br><br>
      <a href="{% url 'main:adminOrdersfilter' 'Processed' %}" class="btn btn-primary" style="width: 150px;">Processed</a>
      <br><br>
      <a href="{% url 'main:adminOrdersfilter' 'Cancel' %}" class="btn btn-primary" style="width: 150px;">Canceled</a>
    </div>
    <hr>
    <div class="panel panel-primary">
      
      <div class="panel-heading" style="text-align:center;">
        <h6 class="panel-title">Recent Orders</h6>
      </div>
      <table class="table table-hover" id="dev-table">
          <tr>
            <th>Processed Orders</th>
            <th>Customer Name</th>
            <!-- <th>Processed Orders</th> -->
            <th>Customer Phone No.</th>
            <th>Order Number</th>
            <th>Order Date</th>
            <th>Order Status</th>
            <th>
            </th>

          </tr>
        
         {% for c in orders %}
         <tr>

           <td>{% total_proceesed_orders c.customerID %}</td>
          <td> {{c.customerID}}</td>
          <td>{{c.customerID.phone}}</td>
          <td> {{c.id}}</td>
          <td>{{c.Order_Date}}</td>
          <td>{{c.orderStatus}}</td>
          <!-- <td>
          </div>
            <form>
              {% csrf_token %}
              <input type="submit" class="Id_submit" value="Get Processed">
              <!-- <button type="submit" class="btn btn-primary shadow px-5 py-2">Add to Cart</button> -->
            <!-- </form>
          </div>
          </td> --> 
          <!-- <td><button class="getProcessed">Get Proceesed</button></td> -->
          <td><a class="btn btn-primary btn-xs" href="{% url 'main:update-order' c.id  %}"><span class="glyphicon glyphicon-edit"></span></a></td>
          <td><a href="{% url 'main:adminorderdetail' c.id %}" target="_blank">View</a></td>
        </tr>
        {% endfor %}





      </table>

  </div>

</div>


{% endblock content %}

main/templates/main/buynow.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}

Order Confirmed


{% endblock main-content %}

main/templates/main/orderDetail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
{% load mathfilters %}
<div class="container">
 <div class="row mt-5">
    <h4>Order Number# {{orderNumber }}</h4>
    <hr>
    <table>
        <tr>
          <th>Product Name</th>
          <th>Details</th>
          <th>Quantity</th>
          <th>Disount</th>
          <th>Selling Price</th>
          <th>Discount Price</th>
        </tr>
      {% for order in orderdetail %}
      <tr>
          <td>{{order.productID.productID}}</td>
          <td>{{order.productID.Description}}</td>
          <td>{{order.quantity}}</td>
          <td>{{order.productID.discount_percentage}} % </td>
          <td>{{order.quantity|mul:order.productID.Price }}</td>
          <td>{{order.price}}</td>
      </tr>
      {% endfor %}
    </table>
    <div class="text-end">
        <p>Total Amount: {{total_amount.price__sum}}</p>
    </div>
    <form action="{% url 'main:orders' %}">
        <div class="text-end">
          <button type="submit" class="btn btn-warning mt-3 px-5 fw-bold">Back To Orders</button>
        </div>
    </form>
 </div>
</div>
{% endblock main-content %}

main/templates/main/orders.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome {{request.user.username.title}}</h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="{% url 'main:orders' %}" class="btn btn-primary">Orders</a></li>
    <!-- <ul>
      <li class="d-grid"><a href="{% url 'main:ordersfilter' 'Pending'  %}" class="btn btn-primary">Pending</a></li>
      <li class="d-grid"><a href="{% url 'main:ordersfilter' 'Completed' %}" class="btn btn-primary">Completed</a></li>
      <li class="d-grid"><a href="{% url 'main:ordersfilter' 'Cancel' %}" class="btn btn-primary">Canceled</a></li>
    </ul> -->
   </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
    <div class="row">
      <!-- Filter buttons -->
      <div class="Container align-self-center">
      <a href="{% url 'main:ordersfilter' 'Pending'  %}" class="btn btn-primary">Pending</a>
      <a href="{% url 'main:ordersfilter' 'Completed' %}" class="btn btn-primary">Completed</a>
      <a href="{% url 'main:ordersfilter' 'Cancel' %}" class="btn btn-primary">Canceled</a>
    </div>
      <table>
        <tr>
          <th><a href="{% url 'main:orders' %}">ID</a></th>
          <th>Order Date</th>
          <th>Order Status</th>
        </tr>
      {% for ord in order %}
      <tr>
          <td><a href="{% url 'main:order-detail' ord.id %}">{{ord.id}}</a></td>
          <td>{{ord.Order_Date}}</td>
          <td>{{ord.orderStatus}}</td>
          {% if "Pending" in ord.orderStatus %}
          {% endif %}
          {% if "Completed" in ord.orderStatus %}
          <td> </td>
          {% endif %}
          {% if "Cancel" in ord.orderStatus %}
          <td>
          </td>
          <td></td>
          {% endif %}
      </tr>
      {% endfor %}
    </table>
    <!-- {% for ord in order %}
    <div class="col-sm-6">
      <div class="card">
       <div class="card-body">
        <h3>Order {{forloop.counter}}</h3>
      {% for e in orderde %}
        {% if ord.id == e.orderID.id %}
        <p>Product Name: {{e.productID}}</p>
        <p>Quantity: {{e.quantity}}</p>
        <p>Price: {{e.price}}</p>
        <p>Order Status: {{ord.Order_Date}}</p>
        <p>Order Date: {{ord.orderStatus}}</p>
        {% endif %}
      {% endfor %}  
       </div>
      </div>
     </div>

   {% endfor %}  -->
  </div>
  </div>
  
 </div>
</div>
{% endblock main-content %}

main/templates/main/productdetail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Product Detail{% endblock title %}
{% block main-content %}
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<script>
   $(document).on("change", '.Price', function (event) {
           event.preventDefault();
           $('#id_price').text($(this).children(":selected").attr("price"));
           $('#id_sale_price').text($(this).children(":selected").attr("sale_price"));
           let id = $('#ItemID').find(":selected").attr('transID');
           console.log('Id : ',id)
         let Url = `{% url 'cart:cart_add' 0 %}`.replace(0,id);
         $('#transactionIDValue').attr('action', Url);
         let formAction = $('#transactionIDValue').attr('action')
         let formAction2 = $('#transactionIDValue').prop('action')
         console.log('form action relative  url : ',formAction)
         console.log('form action full url : ',formAction2)
    });
</script>


<div class="container my-5">
 <div class="row">
  <div class="col-sm-6 text-center align-self-center">
   <img src={{product.product_image.url}} alt="" class="img-fluid img-thumbnail">
   <span class="status">{{product.discount_percentage}} %</span>
    <div class="overlay"></div>
  </div>
  <div class="col-sm-5 offset-sm-1">
   <h2>Product Title: {{product.name}}</h2>
   <hr>
   <p>Description: {{product.description}}</p> <br>
   <div class="d-flex">
    <div class="pricing">
      <p class="price"><span class="mr-2 price-dc" id='id_price'>Rs.  </span><span class="price-sale" id='id_sale_price'>Rs. </span></p>
    </div>
  </div>
   <h4>
    <select class="Price" id="ItemID" style="width: 250px;">
      <option value="none" selected disabled hidden>
        Select an Option
    </option>
    {% for item in transaction %}
    
      <option transID={{item.id}} price={{item.Price}} sale_price={{item.get_sale}} >{{item.AUID.unit}} - {{item.Description}}</option>

    {% endfor %}
  </select>
     <!-- <small class="fw-light text-decoration-line-through">Rs. {{product.selling_price}}  </small> -->
    </h4> <br>
    <form id='transactionIDValue' class="d-inline" method="post">
      {{cart_product_form}}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary shadow px-5 py-2" value="Add To Cart">
      <!-- <button type="submit" class="btn btn-primary shadow px-5 py-2">Add to Cart</button> -->
    </form>
   <!-- <a href="{% url 'main:buy-now' %}" class="btn btn-danger shadow px-5 py-2 ms-4">Buy Now</a> -->
   <h5 class="mt-5">Available Offers</h5>
   <ul>
    <li>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</li>
    <li>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</li>
    <li>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</li>
    <li>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</li>
   </ul>
  </div>
 </div>
</div>
{% endblock main-content %}

main/templates/main/viewCart.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h1 class="text-center mb-5">Shopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3>
    {% for items in cart %}
    {% with product=items.product %}
    <div class="row">
     <div class="col-sm-3 text-center align-self-center">
       <img src={{product.product_image.url}} alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150">
      </div>
     <div class="col-sm-9">
      <div>
       <h5>{{product.name}}</h5>
       <p class="mb-2 text-muted small">Description: {{product.description}}</p>
       <div class="my-3">
        <label for="quantity">Quantity: {{items.quantity}}</label>
        <!-- <a class="minus-cart btn" pid="{{cart.productID.id}}"><i class="fas fa-minus-square fa-lg"></i></a> -->
        <!-- <a class="minus-cart btn"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">{{item.quantity}}</span>
          <a class="plus-cart btn"><i class="fas fa-plus-square fa-lg"></i></a> -->
        <!-- <a class="plus-cart btn" pid="{{cart.productID.id}}"><i class="fas fa-plus-square fa-lg"></i></a> -->
       </div> 
       <div class="d-flex justify-content-between">
           <form action="{% url 'cart:cart_remove' product.id %}" method="post">
               <input type="submit" class="btn btn-sm btn-secondary mr-3" value="Remove Item">
               {% csrf_token %}
           </form>
        <!-- <a class="btn btn-sm btn-secondary mr-3 remove-cart" pid="{{cart.productID.id}}"><strong>Remove Item</strong>  </a> -->
        <p class="mb-0"><span><strong>Rs. {{items.total_price}} </strong></span></p>
        <!-- <p class="mb-0"><span><strong>After Discount: Rs. {{items.total_after_discount}} </strong></span></p> -->
       </div>
      </div>
     </div>
    </div>
    {% endwith %}
    {% endfor %}
    </div>
    </div>
  </div>

  <div class="col-sm-4">
   <div class="card">
    <div class="card-body">
      <h3>Total Amount</h3>
      <ul class="list-group">
       <!-- <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount<span>Rs. <span id="amount">{{amount}}</span></span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>Rs. 70.00</span></li> -->
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total Cost</strong>
         </div>
         <span><strong>Rs. {{cart.get_total_price}}</strong></span>
       </li>
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total After Discount</strong>
         </div>
         <!-- <span><strong>Rs. {{cart.get_total_price_discount}}</strong></span> -->
       </li>
      </ul>
      <div class="d-grid"><a href="{% url 'main:home' %}" class="btn btn-primary">Continue Shopping</a></div>
      <div class="d-grid"><a href="{% url 'main:checkout' %}" class="btn btn-primary">Place Order</a></div>
    </div>
   </div>
  </div>
  
 </div>
</div>
{% endblock main-content %}